#OBJS specifies which files to compile as part of the project 
OBJS = project.cpp 
#OBJ_NAME specifies the name of our exectuable 
OBJ_NAME = Game
all : $(OBJS) 
	g++ $(OBJS) -w -lSDL2 -lSDL2_ttf -lSDL2_mixer -lSDL2_image  -o $(OBJ_NAME)
